name: Editable
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.1.2
  image_picker: 0.8.7+5
  http: any
  provider: ^5.0.0
  url_launcher: any
  sqflite: ^2.0.0
  path: ^1.7.0
  shared_preferences: any
  path_provider: any
  permission_handler: ^11.3.1
  # ext_storage: ^1.0.3
  external_path: ^2.0.1
  open_file: ^3.0.3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: 'dev_assets/app_icon.png'

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/docx_icon.png
